### ISSUE TITLE
Bug on contributors page

### ISSUE THREAD

**Issue by PrP-11** [fossasia/labyrinth#678]
### Expected results
Position of boxes should be aligned in proper way even if their name and info is bigger to fit in the box.
### Actual results
- position gets distorted if name and info field of a box is large.

![bug_1](https://user-images.githubusercontent.com/30981465/35378433-cc0cd286-01d8-11e8-9398-45e0f0857876.png)

### Implementation/Solution Ideas
- fix the size of boxes
### Would you like to work on this
Yes

**Comment by niccokunzmann** [comment]
#671

**Comment by duttaditya18** [comment]
Fixed by @DNS-404

**Comment by himanshuc3** [comment]
Bug still remains, I think!
![screen shot 2018-02-06 at 9 47 16 pm](https://user-images.githubusercontent.com/19166045/35870288-56acd44c-0b87-11e8-93f8-9a2e18dfa5e1.png)
